import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/b7d9211c-26e7-431a-ac24-b0540fb3c00f/air-force-1-07-shoes-rWtqPn.png",
    title: "Nike Air Force 1 '07",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1523 reviews)",
    prevPrice: "$200,00",
    newPrice: "150",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/fc4622c4-2769-4665-aa6e-42c974a7705e/air-force-1-07-shoes-rWtqPn.png",
    title: "Nike Air Force 1 '07",
    star: <AiFillStar className="rating-star" />,
    reviews: "(9853 reviews)",
    prevPrice: "",
    newPrice: "200",
    company: "Nike",
    color: "black", 
    category: "sneakers",
  },

  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/85673388-0487-4c79-8ea2-a3c55d7eb882/sb-dunk-low-pro-aa-skate-shoes.png",
    title: "Nike SB Dunk Low",
    star: <AiFillStar className="rating-star" />,
    reviews: "(255 reviews)",
    prevPrice: "",
    newPrice: "150",
    company: "Nike",
    color: "white",
    category: "skateboarding",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/2a109384-0da3-4189-85e5-7a5e7a6c1660/sb-zoom-blazer-mid-skate-shoes-dXVJLK.png",
    title: "Nike SB Zoom Blazer Mid",
    star: <AiFillStar className="rating-star" />,
    reviews: "(3124 reviews)",
    prevPrice: "$150.00",
    newPrice: "100",
    company: "Nike",
    color: "red",
    category: "skateboarding",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/bb40352b-540b-4437-b32f-fa0525626bd6/superfly-9-elite-mercurial-dream-speed-fg-high-top-football-boot-SsdW2v.png",
    title: "Nike Superfly Mercurial",
    star: <AiFillStar className="rating-star" />,
    reviews: "(2315 reviews)",
    prevPrice: "",
    newPrice: "300",
    company: "Nike",
    color: "green",
    category: "football",
  },
  {
    img: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/aaeeca04-5668-41b2-b947-d8a45a3e7903/phantom-gx-2-elite-lv8-fg-low-top-football-boot-h0Brv4.png",
    title: "Nike Phantom GX ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1532 reviews)",
    prevPrice: "$350,00",
    newPrice: "300",
    company: "Nike",
    color: "blue",
    category: "football",
  },

  {
    img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/7c05f80341d640ba9c0594c7479455db_9366/D.O.N._Issue_5_Shoes_White_IE7799_01_standard.jpg",
    title: "D.O.N. ISSUE 5 SHOES",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1237 reviews)",
    prevPrice: "$100.00",
    newPrice: "50",
    company: "Adidas",
    color: "white",
    category: "basketball",
  },

  {
    img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/eb1fa86363544bb0a86802070f69d26d_9366/Trae_Young_Unlimited_2_Low_Basketball_Shoes_Red_IE7765_01_standard.jpg",
    title: "TRAE YOUNG 2 LOW",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1412 reviews)",
    prevPrice: "$130,00",
    newPrice: "100",
    company: "Adidas",
    color: "red",
    category: "basketball",
  },

  {
    img: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/395205/01/sv01/fnd/EEA/fmt/png/Suede-XL-Sneakers-Unisex",
    title: "Suede XL Sneakers ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1329 reviews)",
    prevPrice: "$100.00",
    newPrice: "50",
    company: "Puma",
    color: "blue",
    category: "sneakers",
  },

  {
    img: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/395205/03/sv01/fnd/EEA/fmt/png/Suede-XL-Sneakers-Unisex",
    title: "Suede XL Sneakers ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1953 reviews)",
    prevPrice: "",
    newPrice: "100",
    company: "Puma",
    color: "red",
    category: "sneakers",
  },
  {
    img: "https://images.vans.com/is/image/Vans/VN000CBS_B7G_HERO?wid=1600&hei=1984&fmt=jpeg&qlt=90&resMode=sharp2&op_usm=0.9,1.7,8,0",
    title: "Zahba Mid Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1477 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "brown",
    category: "skateboarding",
  },
  {
    img: "https://images.vans.com/is/image/Vans/VN0A5FCD_Y52_ALT1?hei=617&wid=492&qlt=50&resMode=sharp2&op_sum=0.9,1.0,8,0",
    title: "Skate Half Cab Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1773 reviews)",
    prevPrice: "$140.00",
    newPrice: "100",
    company: "Vans",
    color: "red",
    category: "skateboarding",
  },
  
];

export default data;